name: Build & Deploy to Pages

on:
  # Only run on commits from master branch
  push:
      branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Build index.html
          run: |
            npm install
            npm run build

        - name: Deploy to gh-pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./build
            publish_branch: gh-pages # Doesn't need to be explicit
            user_name: 'github-actions[bot]'
            user_email: 'github-actions[bot]@users.noreply.github.com'
            commit_message: ${{ github.event.head_commit.message }}
            keep_files: true
            disable_nojekyll: true